# Writing Efficient Python Code

### 1-Foundations for efficiencies

In [2]:
# *A taste of things to come

In [3]:
# *Suppose you wanted to collect the names in the above list that have six letters or more.

In [1]:
names = ['Jerry', 'Kramer', 'Elaine', 'George', 'Newman']

In [5]:
# 1-1
# Print the list created using the Non-Pythonic approach by meeting following condition
# each element in the names list should have six letters or more.

In [2]:
i = 0
new_list= []
while i < len(names):
    if len(names[i]) >= 6:
        new_list.append(names[i])
    i += 1
print(new_list)

['Kramer', 'Elaine', 'George', 'Newman']


In [7]:
# 1-2
# A more Pythonic approach would loop over the contents of names, rather than using an index variable. 
# Print better_list.

In [8]:
better_list = []
for name in names:
    if len(name) >= 6:
        better_list.append(name)
print(better_list)

['Kramer', 'Elaine', 'George', 'Newman']


In [9]:
# 1-3
# The best Pythonic way of doing this is by using list comprehension. Print best_list.

In [10]:
best_list = [name for name in names if len(name) >= 6]
print(best_list)

['Kramer', 'Elaine', 'George', 'Newman']


# Built-in practice: range()

In [11]:
# 1-4
# Create a range object that starts at zero and ends at five. 
# Only use a stop argument.

In [12]:
nums = range(6)
print(type(nums))

<class 'range'>


In [13]:
# * Convert the nums variable into a list called nums_list and print it out.

In [14]:
nums_list = list(nums)
print(nums_list)

[0, 1, 2, 3, 4, 5]


In [15]:
# 1-5
# Create a new list called nums_list2 that starts at one, ends at eleven, 
# and increments by two by unpacking a range object using the star character (*).

In [16]:
nums_list2 = [*range(1,12,2)]
print(nums_list2)

[1, 3, 5, 7, 9, 11]


In [17]:
# *Built-in practice: using a "for" loop for creating a pear of index and name of each element in the the names list:

In [18]:
indexed_names = []
for i in range(len(names)):
    index_name = (i, names[i])
    indexed_names.append(index_name)
print(indexed_names)

[(0, 'Jerry'), (1, 'Kramer'), (2, 'Elaine'), (3, 'George'), (4, 'Newman')]


In [19]:
# 1-6
# Instead of using for i in range(len(names)), 
# update the for loop to use i as the index variable and name as the iterator variable and use enumerate().

In [20]:
indexed_names = []
for i,name in enumerate(names):
    index_name = (i,name)
    indexed_names.append(index_name) 
print(indexed_names)

[(0, 'Jerry'), (1, 'Kramer'), (2, 'Elaine'), (3, 'George'), (4, 'Newman')]


In [21]:
# 1-7
# Rewrite the previous for loop using enumerate() and list comprehension to create a new list:indexed_names_comp.

In [22]:
indexed_names_comp = [(i,name) for i,name in enumerate(names)]
print(indexed_names_comp)

[(0, 'Jerry'), (1, 'Kramer'), (2, 'Elaine'), (3, 'George'), (4, 'Newman')]


In [23]:
# 1-8
# Unpack an enumerate object with a starting index of one
# This time, start the index for enumerate() at one instead of zero.

In [24]:
indexed_names_unpack = [*enumerate(names, 1)]
print(indexed_names_unpack)

[(1, 'Jerry'), (2, 'Kramer'), (3, 'Elaine'), (4, 'George'), (5, 'Newman')]


# Built-in practice: map()

In [25]:
# 1-9 Use map to apply str.upper to convert each name in the list names to uppercase: names_map.

In [26]:
names_map  = map(str.upper, names)

In [27]:
# *Print the type of the names_map

In [28]:
print(type(names_map))

<class 'map'>


In [29]:
# Unpack names_map into a list

In [30]:
names_uppercase = [*names_map]

In [31]:
# *Print the list created above

In [32]:
print(names_uppercase)

['JERRY', 'KRAMER', 'ELAINE', 'GEORGE', 'NEWMAN']


# Practice with NumPy arrays

In [33]:
# * Import numpy as np

In [34]:
import numpy as np

In [35]:
# * Import pandas as pd

In [36]:
import pandas as pd

In [37]:
# * nums list was created.

In [38]:
names = ['Jerry', 'Kramer', 'Elaine', 'George', 'Newman']

In [39]:
# * A two-dimensional numpy array has been loaded into your session (called nums)

In [40]:
nums = np.array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [41]:
# Print second row of nums

In [42]:
print(nums[1,:])

[ 6  7  8  9 10]


In [43]:
# 1-10 Print all elements of nums that are greater than six

In [44]:
print(nums[nums > 6])

[ 7  8  9 10]


In [45]:
# 1-11 Double every element of nums

In [46]:
nums_dbl = nums * 2
print(nums_dbl)

[[ 2  4  6  8 10]
 [12 14 16 18 20]]


In [47]:
# * Replace the third column of nums

In [48]:
nums[:,2] = nums[:,2] + 1
print(nums)

[[ 1  2  4  4  5]
 [ 6  7  9  9 10]]


# Bringing it all together: Festivus!

In [49]:
# 1-12
# Use range() to create a list of arrival times (10 through 50 incremented by 10). 
# Create the list arrival_times by unpacking the range object.

In [50]:
arrival_times = [*range(10, 60, 10)]
print(arrival_times)

[10, 20, 30, 40, 50]


In [51]:
# *Convert arrival_times to an array and update the times.
# *use NumPy broadcasting to subtract three minutes from each arrival time.

In [52]:
arrival_times_np = np.array(arrival_times)
new_times = arrival_times_np - 3

In [53]:
# *print out new_times

In [54]:
print(new_times)

[ 7 17 27 37 47]


In [55]:
# 1-13 Use list comprehension and enumerate to pair guests to new times: guest_arrivals

In [56]:
guest_arrivals = [(names[i],time) for i,time in enumerate(new_times)]

In [57]:
# * print out guest_arrivals.

In [58]:
print(guest_arrivals)

[('Jerry', 7), ('Kramer', 17), ('Elaine', 27), ('George', 37), ('Newman', 47)]


# 3-Gaining efficiencies

## Combining Pokémon names and types

In [61]:
names=['Frillish','Froakie', 'Frogadier', 'Froslass', 'Furfrou', 'Furret', 'Gabite', 'Gallade', 'Galvantula', 'Garbodor', 'Garchomp', 'Gardevoir', 'Gastly', 'Gastrodon', 'Genesect', 'Gengar', 'Geodude', 'Gible', 'Gigalith', 'Girafarig', 'Glaceon', 'Glalie', 'Glameow', 'Gligar', 'Gliscor', 'Gloom', 'Gogoat', 'Golbat', 'Goldeen', 'Golduck', 'Golem', 'Golett', 'Golurk', 'Goodra', 'Goomy', 'Gorebyss', 'Gothita', 'Gothitelle', 'Gothorita', 'Granbull', 'Graveler', 'Greninja', 'Grimer', 'Grotle', 'Groudon', 'GroudonPrimal Groudon']

In [62]:
primary_types = ['Grass', 'Psychic', 'Dark', 'Bug', 'Rock', 'Steel', 'Normal', 'Psychic', 'Water', 'Dragon', 'Rock', 'Normal', 'Grass', 'Electric', 'Rock', 'Poison', 'Fire', 'Normal', 'Rock', 'Rock', 'Bug', 'Rock', 'Fairy', 'Steel', 'Ice', 'Normal', 'Rock', 'Ice', 'Dragon', 'Psychic', 'Water', 'Normal', 'Dragon', 'Ground', 'Ghost', 'Rock', 'Water', 'Water', 'Rock', 'Grass', 'Ice', 'Bug', 'Bug', 'Psychic', 'Steel', 'Grass']

In [63]:
secondary_types=['Ice', np.nan, np.nan, np.nan, 'Flying', 'Rock', np.nan, np.nan, np.nan, 'Flying', 'Ice', np.nan, 'Poison', np.nan, 'Bug', np.nan, np.nan, np.nan, 'Flying', 'Flying', 'Poison', 'Bug', np.nan, 'Rock', 'Flying', np.nan, 'Ice', np.nan, np.nan, np.nan, 'Fairy', 'Fairy', np.nan, 'Psychic', np.nan, 'Water', 'Ground', np.nan, 'Steel', np.nan, np.nan, 'Flying', 'Poison', np.nan, 'Psychic', np.nan]

In [64]:
generations = [1, 1, 1, 5, 3, 5, 1, 6, 1, 6, 5, 5, 4, 6, 3, 4, 2, 5, 2, 5, 4, 1, 1, 2, 6, 5, 5, 6, 6, 1, 4, 5, 6, 2, 6, 1, 3, 2, 4, 1, 5, 3, 5, 5, 1, 5]

In [65]:
pokemon=['Geodude', 'Cubone', 'Lickitung', 'Persian', 'Diglett']

In [ ]:
# 1-15 Combine names and primary_types in a tuple

In [67]:
names_type1 = [*zip(names, primary_types)]

print(*names_type1[:5], sep='\n')

('Frillish', 'Grass')
('Froakie', 'Psychic')
('Frogadier', 'Dark')
('Froslass', 'Bug')
('Furfrou', 'Rock')


In [ ]:
# 1-16 Combine all three lists together

In [68]:
names_types = [*zip(names, primary_types, secondary_types)]

print(*names_types[:5], sep='\n')

('Frillish', 'Grass', 'Ice')
('Froakie', 'Psychic', nan)
('Frogadier', 'Dark', nan)
('Froslass', 'Bug', nan)
('Furfrou', 'Rock', 'Flying')


In [ ]:
# 1-17 Combine five items from names and five items from primary_types

In [69]:
differing_lengths = [*zip(names[:5], primary_types[:5])]

print(*differing_lengths, sep='\n')

('Frillish', 'Grass')
('Froakie', 'Psychic')
('Frogadier', 'Dark')
('Froslass', 'Bug')
('Furfrou', 'Rock')


# Counting Pokémon from a sample

## Collect the count of primary types

In [70]:
# import counter class from collections module.

In [71]:
from collections import Counter

In [72]:
type_count = Counter(primary_types)
print(type_count, '\n')

Counter({'Rock': 9, 'Normal': 5, 'Grass': 4, 'Psychic': 4, 'Bug': 4, 'Water': 4, 'Steel': 3, 'Dragon': 3, 'Ice': 3, 'Dark': 1, 'Electric': 1, 'Poison': 1, 'Fire': 1, 'Fairy': 1, 'Ground': 1, 'Ghost': 1}) 



In [73]:
# 1-18 Collect the count of generations.

In [74]:
gen_count = Counter(generations)
print(gen_count, '\n')

Counter({5: 13, 1: 11, 6: 8, 4: 5, 2: 5, 3: 4}) 



In [75]:
# 1-19 Use list comprehension to get each Pokémon's starting letter

In [76]:
starting_letters = [name[0] for name in names]

In [77]:
# *print out the starting_letters

In [78]:
print(starting_letters)

['F', 'F', 'F', 'F', 'F', 'F', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G', 'G']


In [79]:
# *Collect the count of Pokémon for each starting_letter

In [80]:
starting_letters_count = Counter(starting_letters)
print(starting_letters_count)

Counter({'G': 40, 'F': 6})


# Combinations of Pokémon

In [81]:
# *Import combinations from itertools

In [82]:
from itertools import combinations

In [83]:
# *a pokemon list has been created as follow

In [84]:
pokemon=['Geodude', 'Cubone', 'Lickitung', 'Persian', 'Diglett']

In [85]:
# 1-20 Create a combinations object called combos_obj that contains all possible pairs of Pokémon from the pokemon list. A pair has 2 Pokémon.

In [86]:
combos_obj = combinations(pokemon, 2)

# print out the type of combos_obj
print(type(combos_obj), '\n')

<class 'itertools.combinations'> 



In [87]:
# *Convert combos_obj to a list by unpacking

In [88]:
combos_2 = [*combos_obj]
print(combos_2, '\n')

[('Geodude', 'Cubone'), ('Geodude', 'Lickitung'), ('Geodude', 'Persian'), ('Geodude', 'Diglett'), ('Cubone', 'Lickitung'), ('Cubone', 'Persian'), ('Cubone', 'Diglett'), ('Lickitung', 'Persian'), ('Lickitung', 'Diglett'), ('Persian', 'Diglett')] 



In [89]:
# 1-21 Collect all possible combinations of 4 Pokémon directly into a list

In [90]:
combos_4 = [*combinations(pokemon, 4)]
print(combos_4)

[('Geodude', 'Cubone', 'Lickitung', 'Persian'), ('Geodude', 'Cubone', 'Lickitung', 'Diglett'), ('Geodude', 'Cubone', 'Persian', 'Diglett'), ('Geodude', 'Lickitung', 'Persian', 'Diglett'), ('Cubone', 'Lickitung', 'Persian', 'Diglett')]


# Comparing Pokédexes

In [91]:
ash_pokedex = ['Pikachu', 'Bulbasaur', 'Koffing', 'Spearow', 'Vulpix', 'Wigglytuff', 'Zubat', 'Rattata', 'Psyduck', 'Squirtle']
misty_pokedex = ['Krabby', 'Horsea', 'Slowbro', 'Tentacool', 'Vaporeon', 'Magikarp', 'Poliwag', 'Starmie', 'Psyduck', 'Squirtle']

In [92]:
# 1-22 Convert both lists (ash_pokedex and misty_pokedex) to sets called ash_set and misty_set respectively.

In [93]:
ash_set = set(ash_pokedex)
misty_set = set(misty_pokedex)

In [94]:
# 1-23 Find the Pokémon that exist in both sets

In [95]:
both = ash_set.intersection(misty_set)
print(both)

{'Squirtle', 'Psyduck'}


In [96]:
# 1-24 Find the Pokémon that Ash has, and Misty does not have

In [97]:
ash_only = ash_set.difference(misty_set)
print(ash_only)

{'Pikachu', 'Bulbasaur', 'Vulpix', 'Rattata', 'Wigglytuff', 'Spearow', 'Zubat', 'Koffing'}


In [98]:
# 1-25
# Use a set method to find the Pokémon that are unique to either Ash or Misty 
# (i.e., the Pokémon that exist in exactly one of the Pokédexes but not both).

In [99]:
unique_to_set = ash_set.symmetric_difference(misty_set)
print(unique_to_set)

{'Horsea', 'Bulbasaur', 'Pikachu', 'Magikarp', 'Krabby', 'Koffing', 'Slowbro', 'Vulpix', 'Rattata', 'Poliwag', 'Wigglytuff', 'Vaporeon', 'Tentacool', 'Spearow', 'Zubat', 'Starmie'}


# Searching for Pokémon

In [100]:
# *Convert Brock's Pokédex to a set

In [102]:
brock_pokedex=['Onix', 'Geodude', 'Zubat', 'Golem', 'Vulpix', 'Tauros', 'Kabutops', 'Omastar', 'Machop', 'Dugtrio']

In [103]:
brock_pokedex_set = set(brock_pokedex)
print(brock_pokedex_set)

{'Omastar', 'Dugtrio', 'Machop', 'Kabutops', 'Golem', 'Geodude', 'Zubat', 'Tauros', 'Vulpix', 'Onix'}


In [ ]:
# *Check if 'Psyduck' is in Ash's Pokédex list (ash_pokedex) and if 'Psyduck' is in Brock's Pokédex set (brock_pokedex_set).

In [104]:
print('Psyduck' in ash_pokedex)
print('Psyduck' in brock_pokedex_set)

True
False


In [ ]:
# *Check if 'Machop' is in Ash's Pokédex list (ash_pokedex) and if 'Machop' is in Brock's Pokédex set (brock_pokedex_set).

In [105]:
print('Machop' in ash_pokedex)
print('Machop' in brock_pokedex_set)

False
True


# Gathering unique Pokémon

In [106]:
# 1-26 Write the provided function to collect unique Pokémon names

In [107]:
def find_unique_items(data):
    uniques = []

    for item in data:
        if item not in uniques:
            uniques.append(item)

    return uniques

In [108]:
uniq_names_func = find_unique_items(names)
print(len(uniq_names_func))

46


In [ ]:
# 1-27 Convert the names list to a set to collect unique Pokémon names

In [109]:
uniq_names_set = set(names)
print(len(uniq_names_set))

46


In [ ]:
# 1-28 Check that both unique collections are equivalent

In [110]:
print(sorted(uniq_names_func) == sorted(uniq_names_set))

True


In [ ]:
# *Check that both unique collections are equivalent

In [111]:
print(sorted(uniq_names_func) == sorted(uniq_names_set))

True


In [ ]:
# *Use the most efficient approach for gathering unique items to collect the unique Pokémon types 
# (from the primary_types list) and Pokémon generations (from the generations list).

In [112]:
uniq_types = set(primary_types) 
uniq_gens = set(generations)
print(uniq_types, uniq_gens, sep='\n') 

{'Fairy', 'Ground', 'Electric', 'Steel', 'Ice', 'Dark', 'Poison', 'Ghost', 'Psychic', 'Fire', 'Rock', 'Water', 'Dragon', 'Grass', 'Bug', 'Normal'}
{1, 2, 3, 4, 5, 6}


# Gathering Pokémon without a loop

In [113]:
# 1-29
# Use list comprehension to collect each Pokémon that belongs to generation 1 or generation 2. 
# Save this as gen1_gen2_pokemon.

In [114]:
poke_gens = [1, 1, 1, 5, 3, 5, 1, 6, 1, 6, 5, 5, 4, 6, 3, 4, 2, 5, 2, 5, 4, 1, 1, 2, 6, 5, 5, 6, 6, 1, 4, 5, 6, 2, 6, 1, 3, 2, 4, 1, 5, 3, 5, 5, 1, 5]

In [115]:
poke_names=['Frillish','Froakie', 'Frogadier', 'Froslass', 'Furfrou', 'Furret', 'Gabite', 'Gallade', 'Galvantula', 'Garbodor', 'Garchomp', 'Gardevoir', 'Gastly', 'Gastrodon', 'Genesect', 'Gengar', 'Geodude', 'Gible', 'Gigalith', 'Girafarig', 'Glaceon', 'Glalie', 'Glameow', 'Gligar', 'Gliscor', 'Gloom', 'Gogoat', 'Golbat', 'Goldeen', 'Golduck', 'Golem', 'Golett', 'Golurk', 'Goodra', 'Goomy', 'Gorebyss', 'Gothita', 'Gothitelle', 'Gothorita', 'Granbull', 'Graveler', 'Greninja', 'Grimer', 'Grotle', 'Groudon', 'GroudonPrimal Groudon']

In [116]:
gen1_gen2_pokemon = [name for name,gen in zip(poke_names, poke_gens) if gen < 3]
print(gen1_gen2_pokemon )

['Frillish', 'Froakie', 'Frogadier', 'Gabite', 'Galvantula', 'Geodude', 'Gigalith', 'Glalie', 'Glameow', 'Gligar', 'Golduck', 'Goodra', 'Gorebyss', 'Gothitelle', 'Granbull', 'Groudon']


In [117]:
# * Use the map() function to collect the number of letters in each Pokémon's name within the gen1_gen2_pokemon list. 
# * Save this map object as name_lengths_map.

In [118]:
name_lengths_map = map(len, gen1_gen2_pokemon)
print(name_lengths_map)

In [ ]:
# Combine gen1_gen2_pokemon and name_length_map into a list called gen1_gen2_name_lengths.

In [119]:
gen1_gen2_name_lengths = [*zip(gen1_gen2_pokemon, name_lengths_map)]

In [86]:
print(gen1_gen2_name_lengths[:5])

[]


## Pokémon totals and averages without a loop

In [1]:
pokeman_stats=np.array([ 90,  92,  75,  92,  85,  60],
                       [ 25,  20,  15, 105,  55,  90],
                       [ 65, 130,  60,  75,  60,  75],
                       [ 80,  70,  40, 100,  60, 145],
                       [ 80, 105,  65,  60,  75, 130],
                       [ 70, 110, 180,  60,  60,  50],
                       [ 55,  70,  55,  40,  55,  85],
                       [ 55,  50,  45, 135,  95, 120],
                       [165,  75,  80,  40,  45,  65],
                       [ 75,  70,  90,  70, 105,  80],
                       [ 77,  59,  50,  67,  63,  46],
                       [ 75, 100,  66,  60,  66, 115],
                       [114,  85,  70,  85,  80,  30],
                       [ 90,  75,  85, 115,  90,  55],
                       [ 45,  95,  50,  40,  50,  75],
                       [ 60,  85,  69,  65,  79,  80],
                       [ 90, 110,  80, 100,  80,  95],
                       [120, 120, 120, 120, 120, 120],
                       [ 55, 112,  45,  74,  45,  70],
                       [ 75, 140,  65, 112,  65, 110],
                       [ 70,  90,  70,  60,  60,  40],
                       [ 75, 125, 100,  70,  80,  45],
                       [101,  72,  72,  99,  89,  29],
                       [ 50,  70, 100,  40,  40,  30],
                       [ 90, 85, 100,  95, 125,  85],
                       [103,  60,  86,  60,  86,  50],
                       [123,  77,  72,  99,  92,  58],
                       [ 95, 117, 184,  44,  46,  28],
                       [ 46,  87,  60,  30,  40,  57],
                       [ 75, 125,  70, 125,  70, 115],
                       [100,  50,  80,  60,  80,  50],
                       [ 50,  20,  40,  20,  40,  20],
                       [ 45,  75,  60,  40,  30,  50],
                       [ 40,  40,  55,  40,  70,  55],
                       [ 64 115  65  83  63  65],
                       [ 72 105 115  54  86  68],
                       [ 50  48  43  46  41  60],
                       [ 75 100  63  80  63 116],
                       [100 150 120 120 100  90],
                       [ 38  30  41  30  41  60],
                       [ 60 105  60 120  60 105],
                       [ 40  65  40  80  40  65],
                       [ 40  45  35  30  40  55],
                       [ 72  85  70  65  70  58])

SyntaxError: invalid syntax (<ipython-input-1-0184e59bde79>, line 1)